### ISSUE TITLE
Does Not Redirect

### ISSUE THREAD

**Issue by bfaulk96** [veo-labs/cas-server-mock#1]
I may be missing something, but I have followed the instructions and have tried to hook this up with my local application. My application re-directs to the login page, but when I type in the name of one of the users I specified in my file, it appears to just reload the same login page with more query parameters, instead of redirecting back to the application.

**Comment by maxime-beguin** [comment]
Hi, 

Did you specify a **service** GET parameter when navigating to the CAS page ?
Something like:

`https://your-cas-server.test/cas/login?service=https%3A%2F%2Fyour-client-application.test%2Fyour-cas-ticket-validator-route`

URI decoded **service** parameter: `https://your-client-application.test/your-cas-ticket-validator-route`

**Comment by bfaulk96** [comment]
It appears the initial problem had to do with my application not handling a redirect correctly, but I don't know for sure. Once I got it somewhat working my application started throwing a server error trying to read the XML response token. Either way, I was able to set up my local environment to interact with the actual CAS server I'm trying to, so I do not need a mock server anymore. This issue can be closed regardless. Thanks for the quick reply!

**Comment by maxime-beguin** [comment]
cas-server-mock intends to implement the CAS protocol **3.0.2** has described in [CAS documentation](https://apereo.github.io/cas/5.0.x/protocol/CAS-Protocol.html). 
Which version of the CAS protocol does your application implement ?

Anyway i'm glad you solved your issue with your CAS server.

**Comment by bfaulk96** [comment]
The CAS protocol that my application was designed to implement was CAS 2, since that will be the actual CAS version interacting with my application. It turns out that there were more issues with my configuration than just that, however. Thanks for the timely and useful feedback.

**Comment by maxime-beguin** [comment]
Thanks for your feedback. It brings to our attention that it could be good to make it work with CAS protocol **2.0**.

**Comment by maxime-beguin** [comment]
For your information we added a branch develop (f6daa393d7f74e185928e281110ca98982b5764d) which should be compatible with CAS protocol 2.0.
